### ISSUE TITLE
Plugin should be able to play inline, or embedded in a widget,  just like video player and chewie plugins

### ISSUE THREAD

**Issue by asapJ** [PonnamKarthik/FlutterYoutube#17]
Sometimes use case requires that videos be played inline,  so that other app information can be displayed as well..

@PonnamKarthik @matteocrippa  @suhendra

**Comment by mrbm** [comment]
I went to google IO in may and asked about this, its a bit complicated to make this work and requires some security protocals being created on the youtube end to be interacting with flutter for youtube in a widget windows. Flutter just released to 1.0, I met the project manager of flutter and somebody on the flutter team that was previously on the youtube team.

SO they are very aware of the need, just a lot of things on the list!

**Comment by bhardwajsuresh** [comment]
following link may be helpful :

[https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6](https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6)

**Comment by Shajeel-Afzal** [comment]
Have you found any solution to this @asapJ ?

**Comment by ponnamkarthik** [comment]
Hello @mrbm @Shajeel-Afzal @asapJ @bhardwajsuresh @anticafe Please use my new plugin which is a clone of video_player plugins and it will support videos from youtube 

[ext_video_player](https://pub.dartlang.org/packages/ext_video_player)

Thanks
