### ISSUE TITLE
Version 1.1.3 android is broken (missing ; in java)

### ISSUE THREAD

**Issue by pboos** [PonnamKarthik/FlutterYoutube#21]
Following error happens with the newest version 1.1.3
```
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.1.3/android/src/main/java/io/github/ponnamkarthik/flutteryoutube/FlutterYoutubePlugin.java:20: error: ';' expected
  private static final int YOUTUBE_PLAYER_RESULT = 6646
```

Somehow it seems like that file is totally different from what is currently on github here: https://github.com/PonnamKarthik/FlutterYoutube/blob/master/android/src/main/java/io/github/ponnamkarthik/flutteryoutube/FlutterYoutubePlugin.java

So I guess you probably released 1.1.3 by accident while still working on it?

### Current workaround
Force version 1.1.2 in pubspec.yaml
```
flutter_youtube: "1.1.2" # instead fo "^1.1.2" to force 1.1.2 until 1.1.3 is fixed
```

**Comment by ponnamkarthik** [comment]
fixed in 1.1.4
