### ISSUE TITLE
No implementation found for method listen on channel PonnamKarthik/flutter_youtube_stream

### ISSUE THREAD

**Issue by wazi-mohamed** [PonnamKarthik/FlutterYoutube#23]
nothing happens while click the button

**Comment by geovannyAndrew** [comment]
Same problem occurred to me, but if I try the example project it works fine, I don't know why.

**Comment by geovannyAndrew** [comment]
So what I did was download the zip project, named the folder as flutter_youtube and put it at the same level of pubspec.yaml, and changed the pubspec.yaml lines to this way, and it woks.
![image](https://user-images.githubusercontent.com/4327406/50426709-1fcfb000-0863-11e9-8b8e-4c0e991b1f9a.png)
