### ISSUE TITLE
How to get the Thumbnail?

### ISSUE THREAD

**Issue by michaelchow2324** [PonnamKarthik/FlutterYoutube#35]
Is it possible to get the thumbnail of the video?

**Comment by ponnamkarthik** [comment]
Try this just replace video ID

https://img.youtube.com/vi/<insert-youtube-video-id-here>/default.jpg

For more details check 

https://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api
