### ISSUE TITLE
What is API_KEY ?  (documentation issue)

### ISSUE THREAD

**Issue by brisote** [PonnamKarthik/FlutterYoutube#41]
What is API_KEY where should I get it from ?

**Comment by youssefhad** [comment]
from youtube
https://www.youtube.com/intl/fr/yt/dev/api-resources/

**Comment by brisote** [comment]
maybe it will be good to add this is the documentation (README.md)

**Comment by arbitrarymahi** [comment]
I have added the documentation as requested. Probably the issue can be closed now.
