### ISSUE TITLE
'youtube_flutter' Title, even with full screen. [Android]

### ISSUE THREAD

**Issue by shagal-sajid** [PonnamKarthik/FlutterYoutube#45]
In full-screen mode, when we tilt the screen (even if the screen rotation is off) the video will just go to the non-full-screen mode and there is a header which is says 'youtube_flutter'. So can't use this for production.
![image](https://user-images.githubusercontent.com/33257942/65228462-25071600-dae8-11e9-9a49-01b2bb4d3040.png)

**Comment by atakanyildirim** [comment]
+1

**Comment by YatsenkoDev** [comment]
It is just android AppBar, why not to add opportunity to hide it?
Oh I see it was hidden but Valter Negreiros on 09.10.2019 removed it in his pull request?
