### ISSUE TITLE
Build error by Flutter v1.9.1+hotfix.4

### ISSUE THREAD

**Issue by zxl777** [PonnamKarthik/FlutterYoutube#48]
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

Build Error:
Static method 'playYoutubeVideoByUrl' can't be accessed through an instance.
Try using the class 'FlutterYoutube' to access the method.

**Comment by zxl777** [comment]
Replace the "youtube." to "FlutterYoutube. ", the program fixed.

**Comment by ponnamkarthik** [comment]
please user v2.0.0 and check readme for changes
