### ISSUE TITLE
How to play youtube with the best quality (1080P)?

### ISSUE THREAD

**Issue by zxl777** [PonnamKarthik/FlutterYoutube#49]
How to play youtube with the best quality (1080P)?

**Comment by ponnamkarthik** [comment]
You can change the quality by selecting more options on the player and then change quality

**Comment by zxl777** [comment]
Where to select more options on the player and then change quality ?
![IMG_5033](https://user-images.githubusercontent.com/816448/67154638-7c401680-f332-11e9-851a-6682a664ee4e.PNG)

**Comment by zxl777** [comment]
Android with flutter_youtube: "^2.0.0" worked. I found the quality setting.

But the iOS with flutter_youtube: "^2.0.0" ,the youtube player are woking like the screenshots above. No quality setting.
