### ISSUE TITLE
Error with 1.3.5

### ISSUE THREAD

**Issue by boylenssen** [PonnamKarthik/FlutterYoutube#51]
When building with the latest version, I get the following error:

Compiler message:
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:61:22: Error: Method not found: 'parseColorToHex'.
      'appBarColor': parseColorToHex(appBarColor),
                     ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:62:26: Error: Method not found: 'parseColorToHex'.
      'backgroundColor': parseColorToHex(backgroundColor),
                         ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:88:22: Error: Method not found: 'parseColorToHex'.
      'appBarColor': parseColorToHex(appBarColor),
                     ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:89:26: Error: Method not found: 'parseColorToHex'.
      'backgroundColor': parseColorToHex(backgroundColor),

**Comment by ghost** [comment]
Am also getting same issue........plz fix asap

When building with the latest version, I get the following error:

Compiler message:
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:61:22: Error: Method not found: 'parseColorToHex'.
'appBarColor': parseColorToHex(appBarColor),
^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:62:26: Error: Method not found: 'parseColorToHex'.
'backgroundColor': parseColorToHex(backgroundColor),
^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:88:22: Error: Method not found: 'parseColorToHex'.
'appBarColor': parseColorToHex(appBarColor),
^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_youtube-1.3.5/lib/flutter_youtube.dart:89:26: Error: Method not found: 'parseColorToHex'.
'backgroundColor': parseColorToHex(backgroundColor),

**Comment by boylenssen** [comment]
You can work around it going back to version 1.1.6: `flutter_youtube: 1.1.6`

Op vr 18 okt. 2019 om 13:29 schreef raipradeep <notifications@github.com>:

**Comment by ponnamkarthik** [comment]
fixed v2.0.0

**Comment by ghost** [comment]
Video not playing : Getting error in version v2.0.0

E/YouTubeAndroidPlayerAPI( 4448): Embed config is not supported in RemoteEmbeddedPlayer.

**Comment by ponnamkarthik** [comment]
@raipradeep can you share the video link you are trying to embed

because some videos won't allow embedding

**Comment by ghost** [comment]
Just I have checked, Video is playing fine on real device, but on emulator getting this error. 

E/YouTubeAndroidPlayerAPI( 4448): Embed config is not supported in RemoteEmbeddedPlayer.

Video link : https://www.youtube.com/embed/6dYVVSOLlR0
