### ISSUE TITLE
 does this plugin requires Youtube app installed on the Android device to run?

### ISSUE THREAD

**Issue by andy1xx8** [PonnamKarthik/FlutterYoutube#65]
Hi there.
My name is Andy. 
First, thanks for creating this great plugin for flutter community.

Currently, I have a question about this plugin on Android. When I play a youtube on Android device It doesnt work because it required youtube app installed first.
But this is not required on iOS device. 

So it's true that this plugin requires Youtube app installed on the Android device to run?

Thanks for your help.

**Comment by AhmedNourJamalElDin** [comment]
Following

**Comment by andy1xx8** [comment]
> Following

? What do u mean?

**Comment by AhmedNourJamalElDin** [comment]
I'm following this issue.
I'm interested, too.
I'm facing this issue and I need to know how to solve it 😁

**Comment by faslurrajah** [comment]
I'm following...

I want to draw over the video when it's playing. I put it in a stack to bring a layer in front of video. But it's not working at all. I think it's using YouTube App's default video player inside our app. 

Are there any methods to show something in front of video while playing?

**Comment by ponnamkarthik** [comment]
Hello @logemann @TejaDroid @JSWilProf Please use my new plugin which supports youtube for inline

[ext_video_player](https://pub.dartlang.org/packages/ext_video_player)

Thanks
