### ISSUE TITLE
disable the youtube button in the player which redirects to the youtube app in the device

### ISSUE THREAD

**Issue by shreyask12** [PonnamKarthik/FlutterYoutube#66]
Is there any way to disable or not show the Youtube button in the video player while the video is playing? Can anyone help me on this issue?

**Comment by ponnamkarthik** [comment]
Hello @logemann @TejaDroid @JSWilProf Please use my new plugin which supports youtube for inline

[ext_video_player](https://pub.dartlang.org/packages/ext_video_player)

Thanks
