### ISSUE TITLE
Crash when video ends if onVideoEnded stream is not listened to

### ISSUE THREAD

**Issue by andryr** [PonnamKarthik/FlutterYoutube#9]
How to reproduce : 
`final youtube = FlutterYoutube();
                youtube.playYoutubeVideoById(
                  apiKey: apiKey,
                  videoId: id,
                  fullScreen: false,
                  autoPlay: true,
                );` 
Basically the same code as in the README example.

However it does not crash if we listen to the onVideoEnded stream

**Comment by lance-blo** [comment]
Hi,
I am also having the same issue on both iOS & Android.
Usefull plugin by the way.

**Comment by ponnamkarthik** [comment]
fixed in v1.1.2
